CREATE DATABASE EMP;
USE EMP;
CREATE TABLE EMPLOYEE (EMP_NO VARCHAR(10) NOT NULL,EMP_NAME VARCHAR(10) NOT NULL,DEPT VARCHAR(10) NOT NULL,SALARY INT,DOJ VARCHAR(10) NOT NULL,BRANCH VARCHAR(10) NOT NULL,PRIMARY KEY(EMP_NO));
INSERT INTO  EMPLOYEE(EMP_NO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E101','AMIT','PRODUCTION',45000,'12-MAR-00','BANGLORE');
INSERT INTO  EMPLOYEE(EMP_NO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E102','ANIL','HR',70000,'08-JUL-02','BANGLORE');
INSERT INTO  EMPLOYEE(EMP_NO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E103','SUNITA','MANAGER',12000,'11-JAN-01','MYSORE');
INSERT INTO  EMPLOYEE(EMP_NO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E105','SUNITA','IT',67000,'01-AUG-01','MYSORE');
INSERT INTO  EMPLOYEE(EMP_NO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E106','MAHESH','CIVIL',145000,'20-SEPT-03','MUMBAI');

USE EMP;
SELECT * FROM EMPLOYEE;
SELECT EMP_NO,SALARY FROM EMPLOYEE;
SELECT AVG(SALARY)FROM EMPLOYEE;
SELECT COUNT(EMP_NAME) FROM EMPLOYEE;
SELECT DISTINCT (EMP_NAME) FROM EMPLOYEE;
SELECT SUM(SALARY),COUNT(EMP_NAME) FROM EMPLOYEE GROUP BY EMP_NAME;
SELECT SUM(SALARY) FROM EMPLOYEE WHERE SALARY > 12000;
SELECT EMP_NAME FROM EMPLOYEE ORDER BY EMP_NAME DESC;
SELECT * FROM EMPLOYEE WHERE EMP_NAME='AMIT' AND SALARY > 50000;