CREATE DATABASE DEPARTMENT;
USE DEPARTMENT;

CREATE TABLE DEPT(DEPT_NO INT NOT NULL,DNAME VARCHAR(20) NOT NULL,LOC VARCHAR(20) NOT NULL);

SELECT * FROM DEPT;
USE DEPARTMENT;
ALTER TABLE DEPT ADD COLUMN PINCODE VARCHAR(2) NOT NULL;
ALTER TABLE DEPT DROP COLUMN PINCODE;
ALTER TABLE DEPT CHANGE COLUMN DNAME DEPT_NAME VARCHAR(20);
ALTER TABLE DEPT MODIFY COLUMN LOC CHAR(10);
RENAME TABLE DEPT TO DEPARTMENT;
DROP TABLE DEPARTMENT;
 